# theme: jekyll-theme-cayman
title: Chris Yeh
description: Stanford University, Class of 2019

highlighter: rouge

date_format: "%b %-d, %Y"

# By default, the navbar creates a link for every "page" containing a `title`
# attribute, so long as the title does not include "404". Override the
# default links by defining a `site.header_paths` array:
# header_paths:
# - about.md
# - projects.md

##### BUILD SETTINGS #####
# incremental: true

exclude:
  - env.yml         # conda environment file

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true